name: test_media_generator
description: A simple Dart package to generate media files (images, audio, and video) for testing purposes.
version: 0.0.1
publish_to: none # Remove this line if you wish to publish to pub.dev
repository: https://github.com/MJ12358/test-media-generator

environment:
  sdk: ^3.11.0

# Add regular dependencies here.
dependencies:
  args: 2.7.0
  dart_logz: 0.0.2
  path: 1.9.1
  pubspec_parse: 1.5.0

dev_dependencies:
  dart_lintz: 1.2.1
  test: 1.25.6
